- hosts: localhost
  tasks:
  - name: "Insatll Repo"
    shell: |
      sudo add-apt-repository -y ppa:deadsnakes/ppa
    become: yes
  - name: "Insatll packages"
    shell: |
      apt install -y software-properties-common python3.9 python3.9-distutils 
    become: yes
  - name: "Change Python Version"
    shell: |
      update-alternatives --install /usr/bin/python python /usr/bin/python3.9 3
    become: yes
  - name: "Create venv Python3.9"
    pip: virtualenv="/IaC_ansible/project" 
     virtualenv_python=python3.9
     requirements=/IaC_ansible/requirements.txt